;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-newline
        backspace-delete-highlight-paredit
        beginning-of-buffer
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-toggle-electric-state
        comment-dwim
        electric-pair-backward-delete-char
        electric-pair-backward-delete-char-untabify
        end-of-buffer
        force-insert-tab
        kill-selected-region-default
        newline-and-indent-fix-cc-mode
        paredit-backslash
        paredit-backspace-delete-highlight
        paredit-backward
        paredit-backward-barf-sexp
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-semicolon
        paredit-splice-sexp
        self-insert-command
        slime-eval-last-expression
        slime-space
        smart-tab
        toggle-letter-case
        ))

(setq mc/cmds-to-run-once
      '(
        smart-compile
        helm-swoop
        undo-tree-visualize
        ))
