;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        camel-case-right-word
        coffee-dedent-line-backspace
        paredit-backspace-delete-highlight
        paredit-forward
        smart-tab
        ))

(setq mc/cmds-to-run-once
      '(
        ))
